map_frame: $(arg map_frame)
base_frame: $(arg base_frame)
odom_frame: $(arg odom_frame)
use_tf_scan_transformation: $(arg use_tf_scan_transformation)
use_tf_pose_start_estimate: $(arg use_tf_pose_start_estimate)
pub_map_odom_transform: $(arg pub_map_odom_transform)
map_resolution: $(arg map_resolution)
map_size: $(arg map_size)
map_start_x: $(arg map_start_x)
map_start_y: $(arg map_start_y)
map_multi_res_levels: $(arg map_multi_res_levels)
update_factor_free: 0.4
update_factor_occupied: 0.9
map_update_distance_thresh: 0.4
map_update_angle_thresh: 0.06
laser_z_min_value: -1.0
laser_z_max_value: 1.0
advertise_map_service: true
scan_subscriber_queue_size: $(arg scan_subscriber_queue_size)
scan_topic: $(arg scan_topic)
tf_map_scanmatch_transform_frame_name: $(arg tf_map_scanmatch_transform_frame_name)

# Degub parameters:
# output_timing: false
# pub_drawings: true
# pub_debug_output: true
